#!/bin/bash

python main.py \
  --env_name Env \
  --seed 42 \
  --num_steps 200000 \
  --start_steps 5000 \
  --batch_size 256 \
  --gamma 0.99 \
  --tau 0.005 \
  --diffusion_lr 0.0001 \
  --critic_lr 0.0003 \
  --n_timesteps 20 \
  --beta_schedule cosine \
  --entropy_alpha 0.02 \
  --train_sample 64 \
  --behavior_sample 8 \
  --target_sample 2 \
  --eval_sample 16 \
  --ac_grad_norm 2.0 \
  --q_transform qadv \
  --chosen 1 \
  --q_neg 0.001 \
  --cut 0.8 \
  --policy_freq 1 \
  --weighted \
  --aug \
  --normalize_state True \
  --action_smooth_coef 0.05 \
  --user_move_range 20.0 \
  --reward_scale 1.0 \
  --eav_agg top2 \
  --eav_threshold 10.0 \
  --eav_penalty_coef 2.0 \
  --eav_penalty_cap 20.0 \
  --comm_penalty softplus \
  --comm_threshold 10.0 \
  --comm_penalty_coef 1.0 \
  --comm_softplus_kappa 5.0 \
  --comm_penalty_cap_per_user 15.0 \
  --comm_penalty_cap_total 30.0 \
  --comm_penalty_avg_over_k True \
  --cuda cuda:2